### ISSUE TITLE
request for update to angular 4

### ISSUE THREAD

**Issue by aruribadraiah** [FazioNico/ionic-mean-typescript#1]
could you please update this project to angular 4 and ionic 3 if possible

**Comment by FazioNico** [comment]
Hi @aruribadraiah.
This repository is no longer maintain.
You have a better usage for Ionic MEAN Stack into this repository: MEAN-Ionic-ngRx.
Please see [https://github.com/FazioNico/mean-ionic-ngrx](https://github.com/FazioNico/mean-ionic-ngrx) for more infos 😉
